image: node:20-alpine
cache: { paths: [node_modules/] }
stages: [lint, test]

lint:
  stage: lint
  script:
    - npm ci
    - npm run lint

test:
  stage: test
  script:
    - npm ci
    - npm run lint
    - npm run format:check
    - NODE_ENV=test npm test
